### PR TITLE
Rename binaries until rewrite is finished

### LINKED ISSUE #127: Swap zebrad -> zebra_new, zebra_old -> zebrad until abscissa skeleton is populated.

### PR DESCRIPTION
**Pull request by hdevalence**
Per @dconnolly's suggestion (edit: closes #127), this puts the new abscissa-based binary into `zebrad2` and the old one (to be rewritten) back into `zebrad`.  

This clobbers the existing draft PR I made to start writing Abscissa-based configs for zebrad2, but most of the content of that PR was a) mapping out required configs b) working through how to use abscissa, so I think there's no loss in just making a new branch and copying the meat of the changes over manually (which might have to be done anyways because of abscissa updates in 0.2).

### CODE REVIEW

**Comment by hdevalence** [comment]
Sorry, I didn't see #127 before now so the names don't match the suggestion there, I can change them before we merge this.

**Comment by dconnolly** [comment]
~~I think these builds are failing because the caches are confused about the renames~~

Ah no the `zebra_old` is still in the top-level `Cargo.toml` and not being found.

**Review by dconnolly — CHANGES_REQUESTED** [review]
The top level `Cargo.toml` needs `zebra_old` removed as well, I'm pretty sure that's making the build fail.

**Comment by hdevalence** [comment]
Oops. Updated the `Cargo.toml` files everywhere and made sure that the new zebra is always called `zebra2`

**Review by dconnolly — APPROVED** [review]

**Pull request merged**
