### PR TITLE
Accelerate Travis by removing some steps

### PR DESCRIPTION
**Pull request by hdevalence**
`cargo check` and `cargo build` are subsets of `cargo test`, so by only running tests we can cut the CI time to roughly 1/3.  This also checks the `cargo fmt` version into git so that if rustfmt changes the format rules, we'll get that when we explicitly update it, rather than having random fmt errors.

### CODE REVIEW

**Comment by hdevalence** [comment]
Ah, maybe this isn't a good change: https://github.com/ZcashFoundation/zebra/pull/76#discussion_r299597266

**Comment by dconnolly** [comment]
> `cargo check` and `cargo build` are subsets of `cargo test`, so by only running tests we can cut the CI time to roughly 1/3. This also checks the `cargo fmt` version into git so that if rustfmt changes the format rules, we'll get that when we explicitly update it, rather than having random fmt errors.

`check` is part of `test` while using the same profile, right? And `cargo test` uses a different profile than the default for plain `check` and/or `build`.

Also, this does not pull in all the Rust code in our repo and `check`s it, such as `bin`s that don't have integration tests, but does build them (under `test` profile) as 'bins as unit tests', etc. https://doc.rust-lang.org/cargo/commands/cargo-test.html#cargo_test_target_selection

**Comment by dconnolly** [comment]
> Ah, maybe this isn't a good change: [#76 (comment)](https://github.com/ZcashFoundation/zebra/pull/76#discussion_r299597266)

Yeah it would shave off a little time but we're already caching the results if we stick with the same build profile.

**Comment by hdevalence** [comment]
I'm still not sure that running `cargo check` gives much benefit over just running `cargo test`.  If we want to do a standalone `cargo build`, what if we configured it as a separate job rather than a sequential step?

At least looking at some of the travis runs it doesn't seem that there's much caching going on between `cargo test` and `cargo build`, since the build step recompiles all the crates.

**Comment by dconnolly** [comment]
> I'm still not sure that running `cargo check` gives much benefit over just running `cargo test`. If we want to do a standalone `cargo build`, what if we configured it as a separate job rather than a sequential step?
> 
> At least looking at some of the travis runs it doesn't seem that there's much caching going on between `cargo test` and `cargo build`, since the build step recompiles all the crates.

I think you are correct, check out the thing I just merged, no more `check` and includes the nightly `fmt` job.

**Review by dconnolly — COMMENTED** [review]
I think the main changes in this PR now exist on master, shall I close it?

**Comment by dconnolly** [comment]
> I think the main changes in this PR now exist on master, shall I close it?

Closing without deleting branch as this seems moot.

**Comment by hdevalence** [comment]
SGTM, deleting the branch is fine with me!

**Pull request closed without merging**
